name: Deploy to EC2

on: [push, pull_request]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build with Maven
        run: mvn clean package

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/w1y4f3c3

      - name: Build Docker image
        run: docker build -t decorativka .

      - name: Tag Docker image
        run: docker tag decorativka:latest public.ecr.aws/w1y4f3c3/decorativka:latest

      - name: Push Docker image to ECR
        run: docker push public.ecr.aws/w1y4f3c3/decorativka:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            docker pull public.ecr.aws/w1y4f3c3/decorativka:latest
            docker run -d -p 80:8080 \
              -e SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
              -e SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
              -e JWT_EXPIRATION_TIME=${{ secrets.JWT_EXPIRATION_TIME }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e MAIL_HOST=${{ secrets.MAIL_HOST }} \
              -e MAIL_PORT=${{ secrets.MAIL_PORT }} \
              -e MAIL_USERNAME=${{ secrets.MAIL_USERNAME }} \
              -e MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} \
              -e SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=${{ secrets.SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH }} \
              -e SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=${{ secrets.SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE }} \
              -e TELEGRAMBOT_BOT_USERNAME=${{ secrets.TELEGRAMBOT_BOT_USERNAME }} \
              -e TELEGRAMBOT_BOT_TOKEN=${{ secrets.TELEGRAMBOT_BOT_TOKEN }} \
              -e TELEGRAMBOT_BOT_PATH=${{ secrets.TELEGRAMBOT_BOT_PATH }} \
              -e NOVA_POSHTA_API_KEY=${{ secrets.NOVA_POSHTA_API_KEY }} \
              -e GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
              -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
              -e SERVER_SERVLET_CONTEXT_PATH=${{ secrets.SERVER_SERVLET_CONTEXT_PATH }} \
              public.ecr.aws/w1y4f3c3/decorativka:latest
